[project]
name = "ml-entity-linking"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

authors = [
    {name = "N0kr0s",email = "ka0n5206@gmail.com"}
]
